packages/react/package.json, packages/react/src/fileList/MdFileList.tsx
Added types to buttons so they wont submit potential forms
=> add button types

packages/react/package.json, packages/react/src/modal/MdModal.tsx, stories/Modal.stories.tsx
Lagt til attributt for å kunne styre om modalen skal lukkes når man trykker utenfor.
=> feat: boolean to disable outside click

.storybook/main.js, .storybook/preview.js, assets/preview.css, stories/Contribute.stories.mdx, stories/GettingStarted.stories.mdx
Add pages (stories) for information purposes: getting started + contribute
=> Add introduction pages

packages/react/package.json, packages/react/src/icons/MdBurgerMenuIcon.tsx, packages/react/src/icons/MdBurgerMenuIcon64.tsx, packages/react/src/index.tsx, stories/Icons/BurgerMenuIcon.stories.tsx
Added BurgerMenuIcon to icon library.
=> feat: add burger menu icon

packages/react/package.json
Ny versjon som er deployet riktig til npm. ingen endringer annet enn versjon for riktig pakke
=> fix: update package version for redeployed working pkg

packages/react/package.json, packages/react/src/tabs/MdTabs.tsx, stories/Tabs.stories.tsx
Legger til argument "initialTab" på Tabs, som lar deg kontrollere hvilken tab som er valgt/vises ved første visning.
=> Control tab index initially

packages/react/package.json, packages/react/src/formElements/MdInput.tsx
=> add onKeyDown to MdInput

packages/react/package.json, packages/react/src/formElements/MdAutocomplete.tsx
=> fix: strange typing error only happening in build pipeline

packages/react/package.json
Forgot to re-bump the version after the previous merged PR.
=> fix: bump version

packages/react/package.json, packages/react/src/formElements/MdAutocomplete.tsx, packages/react/src/formElements/MdMultiSelect.tsx, packages/react/src/formElements/MdSelect.tsx
=> Add aria-labelledby to dropdowns

packages/css/package.json, packages/css/src/stepper/stepper.css
Setter flere måte å kalle Sofia Pro fontent på, samt fallback fonter hvis den ikke finnes hos bruker.
=> Styling font fix

packages/css/src/button/README.md, packages/css/src/chips/README.md, packages/css/src/filelist/README.md, packages/css/src/formElements/checkbox/README.md, packages/css/src/formElements/checkboxgroup/README.md, packages/css/src/formElements/fileupload/README.md, packages/css/src/formElements/input/README.md, packages/css/src/formElements/multiselect/README.md, packages/css/src/formElements/radiogroup/README.md, packages/css/src/formElements/textarea/README.md, packages/css/src/help/README.md, packages/css/src/infoTag/README.md, packages/css/src/link/README.md, packages/css/src/messages/AlertMessage.md, packages/css/src/messages/InfoBox.md, packages/css/src/messages/README.md, packages/css/src/modal/README.md, packages/css/src/tabs/README.md, packages/css/src/tile/README.md, packages/css/src/toggle/README.md
Format README files used for documentation of components.
=> chore: format README files used in storybook docs

packages/css/package.json, packages/css/src/button/button.css, packages/css/src/chips/chips.css, packages/css/src/formElements/multiselect/multiselect.css, packages/css/src/formElements/select/select.css
Styling fixes for components:
- Buttons
- Chips
- Select
- Multiselect
Has been packed and tested locally
=> Styling fixes

.github/workflows/npm-md-css.yml, .github/workflows/npm-md-react.yml, .github/workflows/pr-label-checker.yml, .github/workflows/pr-label-prompt.yml
Workflow/actions for å gjøre automatisk bumping av package versions. 
Vil kreve at en label er satt, som brukes for å bumpe riktig versjonstype: major, minor eller patch
=> auto version bump workflows

packages/css/README.md
=> test workflow

packages/css/README.md
=> Test av ny PAT og bruker

.github/workflows/npm-md-css.yml, .github/workflows/npm-md-react.yml
Oppdatert workflow til å bruke variabel fra navn og epost, istedet for secrets
=> fix: removed secrets and changed to vars for transparency

.github/workflows/npm-md-css.yml, .github/workflows/npm-md-react.yml
=> fix: pipeline ref

packages/css/README.md, packages/react/README.md
Test for å se om begge npm actions kan kjøre samtidig
=> test: readme changes for double bump trigger

packages/react/src/formElements/MdInput.tsx, packages/react/src/formElements/MdTextArea.tsx
Add onClick event handlers to MdInput and MdTextArea.
=> Add onClick event handlers to MdInput and MdTextArea

packages/react/src/formElements/MdAutocomplete.tsx
=> fix: make MdAutocomplete close on input click

package-lock.json, package.json, packages/css/src/tooltip/tooltip.css, packages/react/package.json, packages/react/src/tooltip/MdTooltip.tsx
Failing build when deploying to npm in previous commit. Install lodash.debounce package.
=> fix: Install lodash to fix  issue with deploying to npm

package-lock.json
Forgot to update package-lock.json after installing dependencies.
=> fix: Update outdated package-lock.json

package-lock.json, package.json, packages/react/package.json, packages/react/src/tooltip/MdTooltip.tsx
The debounced tooltip trigger is not working well (buggy behavior when the user hovers quickly). Removing functionality until it is implemented in a better way.
=> fix: remove debounce on MdTooltip to avoid strange interactions

packages/react/src/formElements/MdAutocomplete.tsx
The autocomplete placeholder/value does not behave better with the previous fix. Revert the change. Need to figure out what the best interaction with this complex component is.
=> Revert fix autocomplete placeholder interaction

packages/react/src/formElements/MdFileUpload.tsx, packages/react/src/formElements/MdMultiSelect.tsx, packages/react/src/hooks/useFileUpload.ts, packages/react/src/utils/MdClickOutsideWrapper.tsx, stories/Autocomplete.stories.tsx
After adding eslint rules a while back, I left some appearing and more difficult errors unresolved. Fixed these now.
=> fix: Resolve remaining eslint/typescript errors

packages/css/src/filelist/README.md, packages/css/src/filelist/filelist.css, packages/react/src/fileList/MdFileList.tsx, stories/FileList.stories.tsx
=> Add print-action to MdFileList and remove unused classnames

packages/css/src/button/button.css
Adjust the icon-padding for buttons of size "small".
=> Adjust icon-padding for MdButton small size

packages/css/src/formElements/multiautocomplete/README.md, packages/css/src/formElements/multiautocomplete/multiautocomplete.css, packages/css/src/index.css, packages/react/src/formElements/MdAutocomplete.tsx, packages/react/src/formElements/MdMultiAutocomplete.tsx, packages/react/src/index.tsx, stories/MultiAutocomplete.stories.tsx, stories/MultiSelect.stories.tsx
Implement new MultiAutocomple component. A. searchable multi-select.
=> Add MdMultiAutocomplete component

README.md
Update README.md with new information about releases and breaking changes,
=> Add notes on "Releases" and "Breaking changes" to README.md

README.md
=> Update README.md with additional notes on releases

README.md
=> Update README.md on how to test changes locally in own project

README.md
Update example of releasing breaking changes.
=> Update README.md breaking changes example

README.md, packages/react/src/formElements/MdCheckboxGroup.tsx, packages/react/src/formElements/MdMultiAutocomplete.tsx, packages/react/src/formElements/MdMultiSelect.tsx
- Update README with simiplified release instructions
- Remove toString() no longer have any effect
=> Update README with simiplified release instructions

packages/react/src/formElements/MdAutocomplete.tsx, packages/react/src/formElements/MdInput.tsx, packages/react/src/formElements/MdMultiAutocomplete.tsx, packages/react/src/formElements/MdMultiSelect.tsx, packages/react/src/formElements/MdSelect.tsx, packages/react/src/formElements/MdTextArea.tsx
For better accseibility, add aria-describedby to form fields.
=> Add aria-describedby to all form field error message displays

packages/react/src/accordion/MdAccordionItem.tsx, packages/react/src/button/MdButton.tsx, packages/react/src/iconButton/MdIconButton.tsx, packages/react/src/infoTag/MdInfoTag.tsx, packages/react/src/messages/MdAlertMessage.tsx, packages/react/src/tiles/MdTile.tsx, packages/react/src/tiles/MdTileVertical.tsx
Enforce only specific strings to components with the "theme" property.
=> Enforce theme types in all themed components

stories/MultiSelect.stories.tsx, stories/Select.stories.tsx
Fikser en feil i Dokumentasjonen til MdSelect-komponenten
- [ x ] I have performed a self-review and test of my code
- [ x ] I have added label to the PR (`major`, `minor` or `patch`)
=> Fiks Dokumentasjon i henhold til det koden krever

packages/css/src/colors.css, packages/css/src/link/link.css, packages/react/src/link/MdLink.tsx, stories/Link.stories.tsx
Update Link component to match design in Figma
Adjusted css for links and all psuedo-classes.
Added optional icon for links
=> Update Link component to match design in Figma

.github/workflows/deploy-storybook.yml
=> Update node in pipeline

packages/css/src/accordionitem/accordionitem.css
Fix casing in CSS file to to trigger CSS npm package republish new version correctly
=> fix: casing in CSS file comment to trigger CSS npm package republish

README.md, packages/css/README.md
Add font info and disclaimers to readmes
=> Add font disclaimers and -info

pull_request_template.md
Add new point on CSS documentation in the PR template
=> Add new point on CSS documentation in the PR template

packages/css/src/button/button.css, packages/css/src/iconButton/iconButton.css, packages/css/src/tile/tile.css, packages/react/src/button/MdButton.tsx, packages/react/src/iconButton/MdIconButton.tsx, packages/react/src/tiles/MdTile.tsx, packages/react/src/tiles/MdTileVertical.tsx, stories/Button.stories.tsx, stories/IconButton.stories.tsx, stories/Tile.stories.tsx, stories/TileVertical.stories.tsx
Add loading state and indicators to MdButton and MdIconButton
This indicator replaces right or top icon for MdButton and main icon for MdIconButton
=> Add loading state and indicator to button components

stories/GettingStarted.mdx
=> Correct small typo in GettingStarted.mdx installation instructions

packages/react/src/formElements/MdMultiSelect.tsx, packages/react/src/formElements/MdSelect.tsx
Added the disabled prop to the button's disabled attribute, closes #228
=> Fix focus when disabling MdSelect component

packages/css/src/accordionitem/accordionitem.css
Fixes to the expected behavior, closes #227
=> Prevent hover effects on disabled accordion item

packages/react/src/loadingSpinner/MdLoadingSpinner.tsx
Loading spinner was using the "old" spinning icon, switch to new icon
=> Use new loading spinner icon

packages/css/src/formElements/checkboxgroup/checkboxgroup.css, packages/css/src/formElements/combobox/combobox.css, packages/css/src/formElements/input/input.css, packages/css/src/formElements/multiselect/multiselect.css, packages/css/src/formElements/radiogroup/radiogroup.css, packages/css/src/formElements/select/select.css, packages/css/src/formElements/textarea/textarea.css, packages/react/src/formElements/MdCheckboxGroup.tsx, packages/react/src/formElements/MdComboBox.tsx, packages/react/src/formElements/MdInput.tsx, packages/react/src/formElements/MdMultiSelect.tsx, packages/react/src/formElements/MdRadioGroup.tsx, packages/react/src/formElements/MdSelect.tsx, packages/react/src/formElements/MdTextArea.tsx
Spaces between label and element should now be consistent across all form-components.
This PR closes #246 and #255
=> Fix space between label and element

packages/css/src/button/button.css, packages/react/src/button/MdButton.tsx, stories/Button.stories.tsx
New button type: danger secondary
Adjusted paddings and spacings for all buttons according to Figma design
=> New button type: danger secondary

packages/css/src/tooltip/README.md, packages/css/src/tooltip/tooltip.css, packages/react/src/tooltip/MdTooltip.tsx, stories/Tooltip.stories.tsx
MdTooltip now uses Ariakit. Added `mode`-attribute that controls sizing.
=> Rewrite tooltip to use ariakit

README.md
Add section about usage of Ariakit to README.
=> Add section about Ariakit to README

packages/css/src/button/button.css, packages/css/src/chips/chips.css
Chip was missing active hover state. Added CSS fix.
=> fix: Chip missing hover state

stories/GettingStarted.mdx
Fixed typo in GettingStarted.mdx
=> fix: typo in GettingStarted.mdx

packages/css/src/button/button.css
Add border radius to buttons to match Figma and fix incorrect sizing for secondary button small
=> Add border radius to buttons to match Figma

packages/css/src/button/README.md, packages/css/src/button/button.css, packages/react/src/button/MdButton.tsx, stories/Button.stories.tsx
Add large button variant and fix storybook error
=> Add large button variant and fix storybook error

packages/css/src/formElements/combobox/combobox.css, packages/css/src/formElements/select/select.css
fix: Errors in css focus visible
=> fix: Errors in css focus visible

packages/react/src/accordion/MdAccordionItem.tsx, packages/react/src/loadingSpinner/MdLoadingSpinner.tsx, packages/react/src/tooltip/MdTooltip.tsx
Resolves #312, resolves #313, resolves #314, resolves #315
=> Storybook accessibilty plugin reported aria issues

packages/react/src/loadingSpinner/MdLoadingSpinner.tsx
Add "use client" to MdLoadingSpinner
=> Add  "use client" to MdLoadingSpinner

packages/css/src/formElements/combobox/combobox.css
Wrong border color: mdPrimaryColor -> mdColorGrey60
Closes #323
=> Fix MdCombobox border color

packages/css/src/accordionitem/accordionitem.css, packages/react/src/accordion/MdAccordionItem.tsx, stories/AccordionItem.stories.tsx
Fix id for accordion items
Fix css inherited to nested accordions
=> Accordion adjustments

packages/react/src/iconButton/MdIconButton.tsx
Add unmountOnHide to MdTooltip to avoid excessive rerenders
=> Add unmountOnHide to MdTooltip to avoid excessive rerenders

packages/css/src/formElements/input/README.md, packages/css/src/formElements/input/input.css, packages/react/src/formElements/MdInput.tsx, stories/Input.stories.tsx
Updated radius for input component and added support text 
https://github.com/user-attachments/assets/a5cc185c-9862-457d-ad0d-f2186537590a
=> #343 MdInput - Update input component corner radius and add support text

packages/css/src/formElements/combobox/combobox.css, packages/css/src/formElements/select/select.css, packages/css/src/formElements/textarea/textarea.css
added rounded corners to textarea, comboboxes and select
=> (#347) Add rounded corners to text field select combobox and comboboxgrouped

packages/css/src/formElements/input/input.css, packages/react/src/formElements/MdSelect.tsx
- Remove aria-pressed on MdSelect
- Add style rules for hiding number arrows on MdInput for Firefox
Closes #342, closes #339
=> Remove aria-pressed on MdSelect

packages/css/src/iconButton/iconButton.css
Fixed wrong colors for active state on IconButton
=> Adjust iconbutton

README.md
Added section to README about icon and sizes
=> Added section to README about icon and sizes

packages/css/src/formElements/textarea/textarea.css
replace changed css prop that was changed during refactoring of colors and tokens
=> #378 - fixed label spacing
