packages/css/package.json, packages/css/src/formElements/select/select.css
Lagt til z-index på dropdownen slik at den legger seg over andre select knapper under
- [✅] I have performed a self-review and test of my code
=> MALIN-390 fix: z-index

package-lock.json, package.json, packages/css/src/infoTag/infoTag.css, packages/css/src/utils.css, packages/react/package.json, packages/react/src/infoTag/MdInfoTag.tsx, stories/Messages/AlertMessage.stories.tsx
remove auto-animate package and use css transitions/animations
Tydeligvis har auto-animate noen problemer med eldre versjoner av noen bundlers. Dvs at vi får problemer med storybooken dersom vi skal bruke en nyere versjon av auto-animate, siden storybook bruker en eldre versjon av create-react-app. Fjernet auto-animate-pakken og lagde en css transition i stedet, siden den kun ble brukt ett sted.
=> Remove auto-animate

packages/react/package.json, packages/react/src/accordion/MdAccordionItem.tsx
When using MdAccordionItem inside forms, the buttons inside the accordion trigger form submission. Setting type="button" on them fixes this issue.
- [ x ] I have performed a self-review and test of my code
=> fix: add type button to accordion item

packages/react/package.json, packages/react/src/accordion/MdAccordionItem.tsx, packages/react/src/button/MdButton.tsx, packages/react/src/fileList/MdFileList.tsx, packages/react/src/formElements/MdFileUpload.tsx, packages/react/src/formElements/MdMultiSelect.tsx, packages/react/src/index.tsx, packages/react/src/infoTag/MdInfoTag.tsx, packages/react/src/link/MdLink.tsx, packages/react/src/loadingSpinner/MdLoadingSpinner.tsx, packages/react/src/messages/MdAlertMessage.tsx, packages/react/src/messages/MdInfoBox.tsx, packages/react/src/modal/MdModal.tsx, packages/react/src/tabs/MdTab.tsx, packages/react/src/tabs/MdTabTitle.tsx, packages/react/src/tabs/MdTabs.tsx, packages/react/src/tiles/MdTile.tsx, packages/react/src/tiles/MdTileVertical.tsx, packages/react/src/utils/MdClickOutsideWrapper.tsx
Export the prop interfaces for all the exported React components. This was needed to be able to refer to the prop types in other projects, in my case for creating wrapper components in Next.js 13. app router.
- [ X ] I have performed a self-review and test of my code
=> fix: export prop interfaces for React components

packages/react/package.json, packages/react/src/help/MdHelpButton.tsx
When MdHelpButton is used inside a form, clicking the help text button triggers a form submission since it does not have a button type. Add type="button".
=> fix: add type button to help button

package.json, packages/css/package.json, packages/css/src/button/button.css
Changed unit for height, width, right and left on both icon classes so that size and positioning of icon is adjusted accordingly, when font size on the button changes. This is to avoid the current problem, where the icon stays small and wrongly positioned in relation to the text of the button when text has been increased in the user's browser:
Also added flex-shrink: 0 to both icon classes so that icons won't shrink in size if the button is pressed for available space. Reproduceable when minimizing the browser window so that button text wraps across rows:
=> button resizing fix

packages/react/package.json, packages/react/src/button/MdButton.tsx, packages/react/src/link/MdLink.tsx
Changed order of applied props to button and link elements. Otherwise adding a className property when using MdLink or MdButton component will effectively remove the internal classes that style them correctly.
Also made sure that the resulting classes added on the element include both the internal classes and any applied from the outside, so that it is possible to further style the component where it is being used.
NB: If allowing users of the component library to extend styling in this way is accepted, the same logic should be added to all the components, not just MdLink and MdButton as I've done here.
=> Dont override md-classes when adding className prop to button and link

packages/react/package.json, packages/react/src/messages/MdAlertMessage.tsx, packages/react/src/messages/MdInfoBox.tsx, stories/Messages/AlertMessage.stories.tsx, stories/Messages/InfoBox.stories.tsx
Lagt til mulighet for egendefinerte ikoner i infobox og alertmessage. 
På denne måten kan også størrelse, farge og rotasjon på ikonet endres.
Overskrives ved å legge til i argumenter, som for eksempel:
`<MdAlertMessage
label='Feilmeldinger'
theme='error'
customIcon={<MdCloseIcon width={20} height={20} color='white' />}
/>`
=> opportunity to override icons in info boxes

packages/react/package.json, packages/react/src/formElements/MdInput.tsx
Preserve the id set on the input element from incomming props. To allow any parent components to know the input's id and be able to reference the element by that id.
When the incomming id is prefixed with "md-input_" the outside world no longer knows the actual id of the input element and can't reference it correctly. I haven't been able to figure out why it was coded this way originally, and what drawback there would be to just using the incomming id plainly... Hoping to hear from anyone who knows more about the decisions that was made when the component was created :) 
Also desirable to be able to set min/maxLength props on input element, to help users not write longer text than they're allowed. So I added minLength and maxLength to "otherProps" that are just forwarded to the …
=> Preserve input element id

packages/react/package.json, packages/react/src/formElements/MdInput.tsx, packages/react/src/formElements/MdSelect.tsx, stories/Input.stories.tsx, stories/Select.stories.tsx
Added ref-property to MdInput and MdSelect. To be able to focus on the inner input element/button element from the outside, when there is a form error for example.
=> Ref prop on inputs

packages/react/package.json, packages/react/src/modal/MdModal.tsx, packages/react/src/utils/MdClickOutsideWrapper.tsx
When a modal is displayed, with a backdrop, it is not possible via mouse to interact with any other parts of the UI. The user is effectively trapped within the modal and has to close the modal before being able to click links, buttons, etc. on the page below.
The same should be true when using keyboard for navigation: when the modal is displayed it should not be possible to use the tab-key to get to other UI elements below the modal. Before this change, that was possible to do.
I've added a focus trap, that will make sure that when the last focusable element in the modal is reached, the next tab-keypress takes you back to the first focusable element in the modal. So it's not possible to get to the other UI elements of the page below without first closing the modal properly.
=> Focus trap for MdModal component

packages/css/package.json, packages/css/src/formElements/autocomplete/README.md, packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/index.css, packages/react/package.json, packages/react/src/formElements/MdAutocomplete.tsx, packages/react/src/index.tsx, stories/Autocomplete.stories.tsx
Implement autocomplete component. The component allows for default visible dropdown options as well as additional searchable options. The component was made by creating a merged version of MdInput and MdSelect.
=> feat: add MdAutocomplete component

packages/react/package.json, packages/react/src/formElements/MdCheckboxGroup.tsx, packages/react/src/formElements/MdRadioGroup.tsx
Untyped uuid() use caused issues in the build pipeline because type checking is not able to work when uuid() is defined as "any". Hopefully it is fixed now.
=> fix: deploy to npm failed due to missing uuidv4() type

stories/ChipsStories/FilterChip.stories.tsx, stories/ChipsStories/InputChip.stories.tsx
Previous prettier/eslint formatting of the repo did in fact mess something up - in the storybook filter-chip stories. Fixed it.
=> fix: storybook issue caused by eslint formatting

packages/css/package.json, packages/css/src/formElements/input/input.css, packages/react/package.json, packages/react/src/accordion/MdAccordionItem.tsx, packages/react/src/formElements/MdAutocomplete.tsx, packages/react/src/formElements/MdCheckboxGroup.tsx, packages/react/src/formElements/MdInput.tsx, packages/react/src/formElements/MdMultiSelect.tsx, packages/react/src/formElements/MdRadioGroup.tsx, packages/react/src/formElements/MdSelect.tsx, packages/react/src/formElements/MdTextArea.tsx, stories/AccordionStories/AccordionItem.stories.tsx
- Add accessibility features to MdAccordion
- Increase contrast on MdInput suffix
- Let MdAccordionItem close text be definable
Asked designers to update design system in Figma with the higher contrast input suffix.
=> Add a11y to MdAccordion, increase MdInput suffix contrast

packages/css/package.json, packages/css/src/formElements/checkboxgroup/checkboxgroup.css, packages/css/src/formElements/radiogroup/radiogroup.css, packages/react/package.json, packages/react/src/button/MdButton.tsx, packages/react/src/chips/MdFilterChip.tsx, packages/react/src/chips/MdInputChip.tsx, packages/react/src/fileList/MdFileList.tsx, packages/react/src/formElements/MdAutocomplete.tsx, packages/react/src/formElements/MdCheckboxGroup.tsx, packages/react/src/formElements/MdFileUpload.tsx, packages/react/src/formElements/MdInput.tsx, packages/react/src/formElements/MdMultiSelect.tsx, packages/react/src/formElements/MdRadioGroup.tsx, packages/react/src/formElements/MdSelect.tsx, packages/react/src/infoTag/MdInfoTag.tsx, packages/react/src/loadingSpinner/MdLoadingSpinner.tsx, packages/react/src/messages/MdAlertMessage.tsx, packages/react/src/messages/MdInfoBox.tsx
Add aria-labels and aria-hidden to icons, make checkboxgroup and radiogroup fieldsets.
=> Add aria-hidden and aria-labels, make radiogroup and checkboxgroup fieldsets

packages/css/package.json, packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/formElements/fileupload/fileupload.css, packages/css/src/formElements/multiselect/multiselect.css, packages/react/package.json, packages/react/src/formElements/MdAutocomplete.tsx, packages/react/src/formElements/MdFileUpload.tsx, packages/react/src/formElements/MdMultiSelect.tsx, packages/react/src/formElements/MdSelect.tsx, packages/react/src/hooks/useDropdown.ts
- Make the dropdown components MdSelect, MdMultiSelect, and MdAutocomplete accessible: close on escape press and re-focus initial element, tab through content closes dropdown
- Add focus states for MdMulstiSelect and MdAutocomplete
- Fix MdMultiSelect enter press not selecting the focused element
=> Add a11y-features to dropdown-components

packages/react/package.json, packages/react/src/chips/MdFilterChip.tsx, packages/react/src/chips/MdInputChip.tsx, packages/react/src/messages/MdAlertMessage.tsx, packages/react/src/modal/MdModal.tsx, packages/react/src/tabs/MdTabTitle.tsx
Add type="button" to all buttons that did not have the property specified. Buttons without a type can cause issues in some browsers or when used inside a form (unwanted submits).
=> fix: default button type to all buttons

packages/react/package.json, packages/react/src/modal/MdModal.tsx
Ordering of hooks and `if (!open) return null` caused React errors in the console as hooks were being conditionally run (which isn't allowed).
=> fix: console react errors due to conditionally run hooks

md-components.code-workspace, packages/react/package.json, packages/react/src/link/MdLink.tsx, packages/react/src/modal/MdModal.tsx, packages/react/src/tiles/MdTile.tsx, packages/react/src/tiles/MdTileVertical.tsx
Using anchor tags as buttons is not recommended. It causes issues such as not being able to tab to the button. Refactored MdLink, MdTile and MdTileVertical to conditionally render <button or <a depending on the input props.
=> fix: components with onclicks should be buttons

packages/react/package.json, packages/react/src/link/MdLink.tsx
Previous merge of changes to MdLink had incomplete typing causing ts-warning inside projects using the library.
=> fix: incomplete typing of props for MdLink

packages/css/package.json, packages/css/src/formElements/radiogroup/radiogroup.css, packages/react/package.json, packages/react/src/formElements/MdRadioGroup.tsx
The individual radio inputs of MdRadioGroup are absolutely positioned, without having a parent element within the component as relatively positioned. This resulted in weird positioning behaviour in a real life application since the position then became relative to an element further up the DOM, outside of the MdRadioGroup component itself.
Also used option.id when concatenating the options id-prop, instead of option.text which is more likely to be something more than plain text or number. (In my case the option.text-prop was a ReactNode/JSX element, which resulted in an id that looked like `radio_customGroupName_[object: Object]`
=> Fix for MdRadioGroup absolute positioning

packages/css/package.json, packages/css/src/link/link.css, stories/Link.stories.tsx
When refactoring MdLink previously, I forgot to fix the styling of the component when it was rendered as a button. It should look the same as when rendered as an anchor tag now.
=> fix: missing styling on MdLink when rendered as a button

packages/css/package.json, packages/css/src/tile/tile.css
Previous refactor caused additional styles to need to be applied when the components are rendered as buttons.
=> fix: missing styling on MdTile and MdTileVertical when rendered as buttons

packages/css/package.json, packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/formElements/input/input.css, packages/css/src/formElements/multiselect/multiselect.css, packages/css/src/formElements/select/select.css, packages/css/src/help/help.css, packages/css/src/modal/modal.css
- Set base width of dropdown-components to 100% so they will fit the content they are placed in.
- Set margin 1px to input field when number arrows are disabled to avoid it from shifting on active.
- Fix CSS for modal header so the close button doesn't get misaligned when the header is more than one line.
=> fix: bugs in CSS styles for form elements and modal

packages/react/package.json, packages/react/src/tabs/MdTabTitle.tsx, packages/react/src/tabs/MdTabs.tsx, stories/Tabs.stories.tsx
Chips knapper for tabs. Mulighet for å vise ikon når chip er aktiv.
=> Chips tabs

packages/react/package.json, packages/react/src/link/MdLink.tsx, packages/react/src/modal/MdModal.tsx
Added functionality to MdModal to fulfill the accessibility requirements of a dialog:
- role "dialog"
- aria-modal "true"
- aria-label describing the dialog contents
- allow closing of the modal using Escape-key
Also added forwardRef to MdLink, to be able to focus on a link-component. Specifically to be able to bring focus back to the correct place after closing a MdModal.
=> Accessibility on MdModal

stories/AccordionItem.stories.tsx
Adding missing storybook-description for 'expanded' prop of AccordionItem
'expanded' already existed as a prop in AccordionItem, but was not mentioned in the storybook
=> Added missing storybook description for AccordionItem

packages/css/README.md, packages/react/README.md
Nytt forsøk på test av workflows
=> testing and setting up workflows

README.md, packages/css/README.md, packages/react/README.md, pull_request_template.md
Oppdatert readmes (også squashet en haugh commits), og ryddet etter testing.
=> cleanup and update readmes

packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/formElements/multiselect/multiselect.css, packages/css/src/formElements/select/select.css, packages/react/src/formElements/MdAutocomplete.tsx, packages/react/src/formElements/MdMultiSelect.tsx, packages/react/src/formElements/MdSelect.tsx, stories/Autocomplete.stories.tsx, stories/MultiSelect.stories.tsx, stories/Select.stories.tsx
For all three components: MdSelect, MdMultiSelect and MdAutocomplete I have fixed the following:
- labels can now be removed entirely, and padding will not be rendered. 
- "chevron" is rotated when the dropdown is expanded
- size "small", is now the correct size, also in height.
- Select and mulitselect now has a dropdownHeight attribute so the max-height of the dropdown can be customized
- entire "box" of autocomplete is now clickable
- minor styling adjustments across all three components to prevent border-jumping/moving on expansion and focus.
=> Select, multiselect & autocomplete styling fixes

packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/formElements/select/select.css
Mini fix for bug med overlapping av autocomplete, samt forskyving av small select
=> fix: styling issues from last PR

packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/formElements/multiselect/multiselect.css, packages/css/src/formElements/select/select.css
Padding between select-box and label is now the same as other input types
=> fix: add same padding as other inputs

packages/css/package.json, packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/formElements/multiselect/multiselect.css, packages/css/src/formElements/select/select.css
Add padding under help texts for dropdown components where it was missing.
=> fix: add missing padding under dropdown helptexts

packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/formElements/input/input.css, packages/css/src/formElements/multiselect/multiselect.css, packages/css/src/formElements/select/select.css, packages/react/src/formElements/MdAutocomplete.tsx
Fix z-index bugs with dropdown-components, turn off autocomplete for MdAutocomplete, and add margin to input error icon.
=> fix: autocomplete off, z-index dropdowns, input error margin

packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/formElements/input/input.css, packages/css/src/formElements/multiselect/multiselect.css, packages/css/src/formElements/select/select.css, packages/css/src/modal/modal.css, packages/css/src/stepper/README.md, packages/react/src/formElements/MdInput.tsx, packages/react/src/modal/MdModal.tsx, stories/Modal.stories.tsx
Some small adjustments to components to make them more responsive when screen size changes:
1. Changed width settings of select, autocomplete and multiselect elements to max-width instead of width, so they can go smaller than that if there's less space. To fix situations like these (MdSelect-component seen here on mobile screen):
2. Added "small"-width to MdInput outer wrapper. Even though I use MdInput with size="small" here, it still takes up all that extra width because the outer wrapper didn't have a width restriction like the inner wrapper does when size is set to small:
3. We needed a modal in our form, that doesn't change size according to it's content because the content changes a lot when used so the modal would "jump around" both horizontally and vertically as the user was …
=> Fixed responsiveness of inputs and modal

packages/css/src/formElements/input/input.css, packages/css/src/formElements/textarea/textarea.css, packages/react/src/formElements/MdAutocomplete.tsx
Use outline instead of border to avoid input content or content below it shifting on focus.
Also fix small a11y bug (mismatch of id's).
=> fix: MdInput, MdTextAre shifting position on focus

packages/react/src/formElements/MdInput.tsx, stories/Input.stories.tsx
Add support for string alternative for max and min property (previously only number) on input component. 
This will make it possible to set min and max value for input-components with type "date", maybe other types as well, I haven't checked.
Added the min and max property to the input-story to make the properties testable from det storybook
=> Add support for string alternative for max and min property on input component

packages/react/src/formElements/MdAutocomplete.tsx, stories/Autocomplete.stories.tsx
Adds the variable `amountOfElementsShown` to the `MdAutocomplete` component. It makes it possible to set a maximum amount of elements shown in the dropdown, which is useful when you have a very long list of options.
It has a default value of `null`, that returns the whole list. So it does not change existing instances of this component.
=> RB-2548: Add max element amount to MdAutocomplete

packages/react/src/modal/MdModal.tsx
Experienced the MdModal-component not having focus trap enabled. This fix makes sure the useEffect that registers the eventhandler for focus trapping is run after modal is opened.
=> Fix for focus trap not attached

packages/css/src/messages/AlertMessage.md, packages/css/src/messages/alertMessage.css, packages/react/src/messages/MdAlertMessage.tsx, stories/Messages/AlertMessage.stories.tsx
Some enhancements to MdAlertMessage-component:
1. Fix so that icon is not shrinked when label wraps across lines:
2. New prop to control alignment between icon and content/label. Default is still centered, but gives the possibility to set either start or end:
3. Added type ReactNode to label-prop, to allow contents of AlertMessage to be more advanced than a plain string. For example for text split up by controlled new lines. Or to be able to add a heading, bulleted list etc.
=> MdAlertMessage with ReactNode contents

packages/react/src/messages/MdAlertMessage.tsx, packages/react/src/messages/MdInfoBox.tsx
Added optional property "role" on MdAlertMessage and MdInfoBox. To be able to specify correct role from outside, based on use case. Role "status", "alert" and "alertdialog" are all possibly correct roles, depending on how the components are used in context of the application.
=> Add role prop on alert message and info box

packages/react/src/formElements/MdAutocomplete.tsx
Opplevde problemer med forrige commits feaure. Fant en annen feil i prosessen:
Placeholder-logikken er kopiert fra select der det ikke finnes "placeholder" fordi det brukes buttons. Derfor kunne vi endre placeholder-logikk i denne komponenten.
=> Revert autocomplete close on input click (#120) and fix placeholder interaction

packages/css/src/button/button.css, packages/react/src/button/MdButton.tsx, stories/Button.stories.tsx
Implement tertiary button.
Design has been approved and added to the design system Figma by our projects' designer.
=> Add tertiary-theme to MdButton

packages/css/src/formElements/radiobutton/README.md, packages/css/src/formElements/radiobutton/radiobutton.css, packages/css/src/index.css, packages/react/src/formElements/MdRadioButton.tsx, packages/react/src/index.tsx, stories/Button.stories.tsx, stories/Checkbox.stories.tsx, stories/CheckboxGroup.stories.tsx, stories/FileList.stories.tsx, stories/RadioButton.stories.tsx, stories/RadioGroup.stories.tsx
Similarly to MdCheckbox and MdCheckboxGroup, MdRadioGroup needed a "single" component option, to allow for more flexibility.
In addition, clean up some old story-documentation code to follow one standard.
Example of a situation where single radiobuttons is useful (keep in mind to add your own a11y when using these solo):
=> Add MdRadioButton component

packages/css/src/button/README.md, packages/css/src/tooltip/tooltip.css, stories/Tooltip.stories.tsx
The Storybook docs for MdTooltip did not have updated controls. Added missing controls, fixed minor CSS issue and added tertiary theme to MdButton README example docs.
=> fix: MdTooltip missing controls in Storybook

packages/css/src/button/button.css
Padding on buttons when using left/right-icon was incorrect. Fixed. This was especially apparent when using a small button with an icon.
=> fix: Incorrect button padding when using left/right-icon

packages/react/src/formElements/MdInput.tsx, stories/Input.stories.tsx
Expanded the type of the suffix-prop on MdInput, to be able to add an icon, or button there instead of just text. Specific use case that triggered the need for change is having an icon button for clearing the input:
=> More advanced input suffix

packages/react/src/tooltip/MdTooltip.tsx
Add property on MdTooltip to define a class name for the tooltip div, for example, a max width, rather than having to define the content with an additional styled div.
=> Add tooltipClass to MdTooltip

.eslintrc.json, package-lock.json, package.json
Remove legacy eslint-prettier-plugin causing unnecessary error-squigglies and bloat.
Eslint and prettier will still work as normal.
With the legacy plugin, prettier essentially runs twice, once by eslint and once on its own.
=> Remove legacy eslint plugin

packages/react/src/fileList/MdFileList.tsx, stories/FileList.stories.tsx
Limit which files are printable based on file ending. Allow the user of the component to modify which filetypes should be printable.
=> Show print icon in MdFileList only for printable file types

packages/css/src/button/button.css
MdButton margin between the left/right icons did not correspond to the design system specification. Fixed.
=> Add additonal margin between MdButton content and left/right icons

packages/react/src/tooltip/MdTooltip.tsx
=> Add role="tooltip" to MdTooltip to avoid a11y errors with its aria-label

packages/react/src/tiles/MdTile.tsx, packages/react/src/tiles/MdTileVertical.tsx
Icons in MdTile and MdTileVertical were not hidden from screen readers. Fixed.
=>  Hide icons in MdTile and MdTileVertical from screen readers

packages/css/src/accordionitem/accordionitem.css, packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/formElements/multiautocomplete/multiautocomplete.css, stories/MultiAutocomplete.stories.tsx
Fixed a couple of CSS bugs:
- Prefix icon not showing when disabled for Autocomplete and MultiAutocomplete
- No visual focus for AccordionItem header
=> fix: Autocomplete prefix icons not showing when component disabled and missing visual focus for AccordionItem header

packages/react/src/link/MdLink.tsx, packages/react/src/tiles/MdTile.tsx, packages/react/src/tiles/MdTileVertical.tsx
It was not possible to add button/achor-props like aria-attributes or classname to MdLink, MdTile and MdVerticalTile. Converted their props to types and extended correctly.
=> Correctly extend MdLink and MdTile with button/anchor-attributes

packages/css/src/tile/tile.css
Define min and max width for MdTile, let it flex otherwise.
Decided after discussion with designers and specification in MD design system.
=> Define min and max widths for MdTile

packages/css/src/tile/README.md, packages/css/src/tile/tile.css, packages/react/src/tiles/MdTile.tsx, stories/Tile.stories.tsx
Add modes "medium" and "small" to MdTile following new definition in design system.
=> Add multiple sizes to MdTile

packages/css/src/tile/README.md, packages/css/src/tile/tile.css, packages/react/src/tiles/MdTile.tsx, stories/Button.stories.tsx, stories/Tile.stories.tsx
Add fullWidth option to MdTile. This is useful for i.e mobile views and can be combined with mode="small".
=> Add fullwidth option to MdTile

packages/react/src/tooltip/MdTooltip.tsx
Previously aria-hidden had been applied to the children the tooltip is wrapping content rather than the tooltip content itself. This caused errors in the console when the focus was trying target to the content.
=> fix: aria-hidden was applied to the wrong div inside MdTooltip

packages/react/src/formElements/MdAutocomplete.tsx, packages/react/src/formElements/MdMultiAutocomplete.tsx
revert: fix: When escaping or pressing enter inside autocompletes, displayvalue was shown and user could no longer type .  (#157)
New bug introduced when fixing the above. Roll back to previous bug and fix the new bug in a different PR.
=> revert: fix: (#157) 

packages/react/src/formElements/MdFileUpload.tsx, stories/FileUpload.stories.tsx
Adds three new optional arguments to the MdFileUpload component
- uploadTexts: makes it possible for developers to change static 'Dropp en fil her eller velg fra denne maskinen' text
- automaticTrigger: boolean which makes component run onUpload every time the filelist changes (avoids users having to click 'Last opp' every time if desired)
- hideButtons: boolean which hides the 'Avbryt' and 'Last opp' buttons. Meant to be used together with automaticTrigger.
- [ x ] I have performed a self-review and test of my code
- [ x ] I have added label to the PR (`major`, `minor` or `patch`)
=> MdFileUpload expansion

packages/css/src/formElements/radiobutton/radiobutton.css
Add min width to radiobutton to avoid incorrect width in small containers
=> fix: add flex-shrink to radiobutton to avoid incorrect width in small containers

packages/css/src/formElements/radiogroup/README.md, packages/css/src/formElements/radiogroup/radiogroup.css, packages/react/package.json
After refactoring the radio group option to a separate component a while back, unused styles for the radio group option were left behind in radiogroup.css. Remove them. Update README.md for MdRadioGroup.
=> Remove unused radiogroup styles

packages/css/src/accordionitem/accordionitem.css
The margin bottom does not seem to be very helpful. Is this something we can remove?
I.e, I want to use the MdAccordion items inside scrollable container, and now the last item creates a weird gap at the bottom.
I can override the behavior, but it seems like a strange default.
=> Remove margin bottom on accordionitem

packages/css/src/button/button.css
Different heights on the secondary button due to the border. Subtract border from padding.
=> fix: Subtract border on secondary button to make it the same size as primary/warning/tertiary

stories/Icons/AllIconsGallery.stories.tsx
Add missing MdSortingActiveIcon to gallery in storybook.
=> fix: Add missing MdSortingActiveIcon to gallery

.gitignore, packages/css/src/chips/chips.css
Add inner outline for focused selected chips
Updated gitignore
=> Adjust chips focus

packages/css/src/formElements/autocomplete/autocomplete.css, packages/css/src/formElements/multiautocomplete/multiautocomplete.css, packages/react/src/formElements/MdAutocomplete.tsx, packages/react/src/formElements/MdMultiAutocomplete.tsx
This pull request replaces deprecated icons that were left behind from a previous major release.
* Removed the `rotate: 90deg;` property from the `autocomplete.css` file.
* Removed the `rotate: 90deg;` property from the `multiautocomplete.css` file.
* Replaced `MdChevronIcon` with `MdIconKeyboardArrowDown` in the `MdAutocomplete` component.
* Replaced `MdXIcon` with `MdIconClose` in the `MdAutocomplete` component.
* Replaced `MdChevronIcon` with `MdIconKeyboardArrowDown` in the `MdMultiAutocomplete` component.
=> Replace remaining deprecated icons in autocomplete components

packages/css/src/button/README.md, packages/css/src/chips/README.md, packages/css/src/filelist/README.md, packages/css/src/formElements/autocomplete/README.md, packages/css/src/formElements/checkbox/README.md, packages/css/src/formElements/input/README.md, packages/css/src/formElements/multiautocomplete/README.md, packages/css/src/formElements/multiselect/README.md, packages/css/src/formElements/radiobutton/README.md, packages/css/src/formElements/radiogroup/README.md, packages/css/src/formElements/select/README.md, packages/css/src/formElements/textarea/README.md, packages/css/src/iconButton/README.md, packages/css/src/infoTag/README.md, packages/css/src/link/README.md, packages/css/src/messages/AlertMessage.md, packages/css/src/messages/InfoBox.md, packages/css/src/messages/README.md, packages/css/src/modal/README.md, packages/css/src/tile/README.md, packages/css/src/toggle/README.md, packages/css/src/tooltip/README.md
Replace 'className' with 'class' in all css examples in readme-files.
=> use 'class' in all html examples

packages/react/src/formElements/MdCheckbox.tsx
Added the disabled attribute that was missing in MdCheckbox, closes #248
=> Fixes both the checkbox and checkbox group components disabled behavior

packages/react/src/stepper/MdStep.tsx, packages/react/src/tabs/MdTab.tsx
If MdStep or MdTab is imported in a server comp and passed to their parent-components MdStepper and MdTabs, props will not be passed because client comps can't pass props to server comps. Fix by adding "use client" to MdTab and MdStep.
=> Add "use client" to MdTab and MdStep 

packages/react/src/formElements/MdComboBox.tsx, packages/react/src/formElements/MdComboBoxGrouped.tsx
Set includesBaseElement to false in MdComboBox and MdComboBoxGrouped to false to avoid unnecessary moving into the input field when navigating with arrows. The input is always active, so we don't need to move into it.
=> Set includesBaseElement to false in MdComboBox and MdComboBoxGrouped

packages/css/src/tabs/README.md, packages/css/src/tabs/tabs.css, packages/react/src/tabs/MdTabs.tsx, stories/Tabs.stories.tsx
Added compact variant of tabs, as per this design: https://www.figma.com/design/6BUqOC0xQZz6AggPvI2iSR/Komponenter?node-id=1842-9300&p=f&t=QLNj51axppt4SPQb-0
Note: I have not made any changes to the styling to account for chips = true, as this is not part of the design.
=> Tabs: Add compact variant

packages/css/src/button/button.css
I noticed the left/right icon in MdButton would be off center if the Icon itself is not square. Added CSS to fix it.
Before:
After:
=> Add align-content to left and right icons in button styles

packages/css/src/button/button.css, packages/css/src/formElements/combobox/combobox.css, packages/css/src/index.css
After upgrading to Tailwind v4, the background color became transparent on the MdCombobox. A white background color has been explicitly added for other dropdown components, but not for MdCombobox, so I also added it there.
I also noticed this global button style overriding my tailwind styles. Turns out its from md-components. I removed it. @ohp-inmeta can you verify it should be removed? Reading the message, seems like the fix should be done in the project.
=> fix: Add background color to combobox input and remove global button style

packages/css/src/accordionitem/accordionitem.css
fix: Correct outline offset of accordionitem to match Figma
=> fix: Correct outline offset of accordionitem to match Figma

packages/react/src/accordion/MdAccordionItem.tsx
fix: modify tabindex on AccordionItem details to avoid double tabbing
=> fix: modify tabindex on AccordionItem details to avoid double tabbing

packages/css/src/button/button.css
This PR replaces all usages of the :enabled pseudo-class in the button CSS with :not(:disabled):not([disabled]). The change ensures that styles for .md-button, including .md-button--secondary, apply correctly when used with anchor (<a>) tags, not just native button elements. This improves flexibility and accessibility for custom components that use anchor tags styled as buttons.
- [✅] I have performed a self-review and test of my code
- [✅] I have added label to the PR (`major`, `minor` or `patch`)
=> Update button CSS selectors for better anchor tag compatibility

packages/css/src/formElements/combobox/combobox.css, packages/react/src/formElements/MdComboBox.tsx, packages/react/src/formElements/MdComboBoxGrouped.tsx
Search is now reset when the combobox is closed.
Fixes combobox toggle and focus styling
The toggle button now correctly reflects the open/closed state of the popover, ensuring consistent user interaction. There was a problem where the popover would not close if it was opened by clicking in the searchbar and trying to close it width the arrow-button.
Also, the focus styling on the input is updated to maintain a consistent appearance, specifically addressing border radius inconsistencies when the combobox is focused but not expanded. This enhances the visual appeal and user experience.
Closes #285
=> Reset search value on combobox close

packages/css/src/button/button.css
Removes the border-radius property from the small and large button size modifiers. All button size should use same border-radius, according to Figma
Closes #365
=> Removes specific border radius from button sizes
